name: Extract-JAR

on:
  workflow_dispatch:  # Manual Events
        
jobs:
  extract-jar:
    runs-on: ubuntu-latest
    
    steps:
      - name: clone repo
        uses: actions/checkout@v3
       
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
          
      - name: build debris
        run: |
          ./gradlew clean
           ./gradlew debris:jar
        
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Debris JAR
          path: ./debris/build/libs/*.jar
